[program:queue-worker-1]
process_name=worker-1
command=php /var/www/html/artisan queue:work redis --sleep=1 --tries=3 --max-time=3600 --max-jobs=1000 --memory=512
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-1.log
stopwaitsecs=10
stopsignal=QUIT

[program:queue-worker-2]
process_name=worker-2
command=php /var/www/html/artisan queue:work redis --sleep=1 --tries=3 --max-time=3600 --max-jobs=1000 --memory=512
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-2.log
stopwaitsecs=10
stopsignal=QUIT

[program:queue-worker-3]
process_name=worker-3
command=php /var/www/html/artisan queue:work redis --sleep=1 --tries=3 --max-time=3600 --max-jobs=1000 --memory=512
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-3.log
stopwaitsecs=10
stopsignal=QUIT

[program:queue-worker-4]
process_name=worker-4
command=php /var/www/html/artisan queue:work redis --sleep=1 --tries=3 --max-time=3600 --max-jobs=1000 --memory=512
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-4.log
stopwaitsecs=10
stopsignal=QUIT
